# Generated by Django 5.2 on 2025-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblecheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblecheck',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
