# Generated by Django 5.2 on 2025-04-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dday',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='제목/내용'),
        ),
        migrations.AddField(
            model_name='dday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ddays', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
