# Generated by Django 5.2 on 2025-04-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
