# Generated by Django 5.2 on 2025-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_profile'),
        ('toolhub', '0006_tool_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('free', '프리'), ('basic', '베이직'), ('premium', '프리미엄')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frequent_tools',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='toolhub.tool'),
        ),
    ]
