# Generated by Django 5.2 on 2025-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0003_toolrunlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='link',
            field=models.URLField(blank=True, help_text='툴 실행용 링크 주소', null=True),
        ),
    ]
