# Generated by Django 5.2 on 2025-04-17 07:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0004_tool_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='이 툴의 관리자', related_name='managed_tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
