# Generated by Django 5.2 on 2025-04-23 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0005_tool_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='creators',
            field=models.ManyToManyField(blank=True, help_text='이 툴을 만든 사람들', related_name='created_tools', to=settings.AUTH_USER_MODEL),
        ),
    ]
