# Generated by Django 5.2 on 2025-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolhub', '0007_category_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='이 카테고리에 대한 간단한 설명을 입력하세요.'),
        ),
    ]
