# Generated by Django 5.2 on 2025-09-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(verbose_name='층')),
                ('room_number', models.CharField(max_length=10, verbose_name='호수')),
                ('resident', models.CharField(blank=True, max_length=50, null=True, verbose_name='거주자')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_residences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-floor', 'room_number'],
            },
        ),
    ]
