# Generated by Django 5.2 on 2025-08-22 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='질문')),
                ('category', models.CharField(choices=[('daily', '일상'), ('emotion', '감정'), ('social', '관계/사회성'), ('imagine', '상상'), ('choice', '선택')], default='daily', max_length=20, verbose_name='카테고리')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='난이도(1~3)')),
                ('min_age', models.PositiveSmallIntegerField(default=3, verbose_name='권장 최소 나이')),
                ('max_age', models.PositiveSmallIntegerField(default=7, verbose_name='권장 최대 나이')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='기록일')),
                ('child_name', models.CharField(blank=True, max_length=30, verbose_name='아이 이름(선택)')),
                ('answer_text', models.TextField(blank=True, verbose_name='아이의 대답 / 관찰')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyq_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='dailyq.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question', 'date')},
            },
        ),
    ]
