# Generated by Django 5.2 on 2025-07-17 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripter', '0002_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('time_of_day', models.CharField(blank=True, max_length=50)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripter.script')),
            ],
        ),
    ]
