# Generated by Django 5.2 on 2025-07-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripter', '0003_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('order', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripter.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scripter.scene')),
            ],
        ),
    ]
