# Generated by Django 5.2 on 2025-04-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NTKIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NTK Internal Tools', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ntk_intro/')),
                ('description', models.TextField()),
                ('current_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('changes', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='ntkintro.ntkintro')),
            ],
        ),
    ]
