# Generated by Django 5.2 on 2025-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carded', '0002_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
