# Generated by Django 5.2 on 2025-09-20 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=64)),
                ('style', models.CharField(blank=True, max_length=20)),
                ('lang', models.CharField(blank=True, max_length=10)),
                ('seed', models.CharField(blank=True, max_length=32)),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분', max_length=128)),
                ('copied_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_nicknames', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'text')},
            },
        ),
    ]
